# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages 
RUN pip install --no-cache-dir transformers torch fastapi uvicorn

# Expose the port the app runs on
EXPOSE 8000

# Run uvicorn to start the NLP zeroshot  app
CMD ["uvicorn", "classify:app", "--host", "0.0.0.0", "--port", "8000"]
